stages:
  - test
  - deploy

run_tests:
  stage: test
  
  script:
  - jekyll build --config _config_dev.yml

pages:
  stage: deploy
  script:
  - jekyll build --config _config_dev.yml
  - mv _site public
  artifacts:
    paths:
    - public
  only:
  - master
